require: rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Metrics/AbcSize:
  Max: 32
  Exclude:
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 35
  Exclude:
    - test/**/*.rb

Metrics/ParameterLists:
  CountKeywordArgs: false
  MaxOptionalParameters: 4

Metrics/PerceivedComplexity:
  Max: 10

# Can allow short heredoc delimiters in the tests.
Naming/HeredocDelimiterNaming:
  Exclude:
    - test/**/*.rb

Naming/MethodParameterName:
  AllowedNames: a, b, c, s1, s2, w, x, x1, x2, y, y1, y2, z

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  MinSize: 4
  Exclude:
    - test/**/*.rb
