#!/usr/bin/env ruby
# frozen_string_literal: true

# Advent of Code 2023
#
# Robert Haines
#
# Public Domain

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'aoc2023/extra/cli'

days = AOC2023::Extra::CLI.parse_params(ARGV)

unless days
  warn 'Usage: aoc-2023 <day>'
  exit 1
end

days.each do |day|
  AOC2023::Extra::CLI.run_day(day)
end
